### ISSUE TITLE
filter-file-path does not work with relative paths

### ISSUE THREAD

**Issue by hahn-kev** [leonardochaia/dotnet-affected#105]
I'm trying to use dotnet affected like this `dotnet affected --filter-file-path .\LexBox.sln` and it throws this error:
```
Unhandled exception: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: .\LexBox.sln unexpectedly not a rooted path
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInternalRooted(String value)
   at Microsoft.Build.Construction.SolutionFile.set_FullPath(String value)
   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)
   at DotnetAffected.Core.SolutionFileProjectDiscoverer.DiscoverProjects(IDiscoveryOptions options) in /_/src/DotnetAffected.Core/ProjectDiscovery/SolutionFileProjectDiscoverer.cs:line 12
   at DotnetAffected.Core.ProjectDiscoveryManager.DiscoverProjects(IDiscoveryOptions options) in /_/src/DotnetAffected.Core/ProjectDiscovery/ProjectDiscoveryManager.cs:line 20
   at DotnetAffected.Core.ProjectGraphFactory.BuildProjectGraph() in /_/src/DotnetAffected.Core/ProjectGraphFactory.cs:line 29
   at Affected.Cli.Commands.InvocationContextExtensions.BuildAffectedExecutor(InvocationContext ctx) in /_/src/dotnet-affected/Commands/Binding/InvocationContextExtensions.cs:line 18
   at Affected.Cli.Commands.InvocationContextExtensions.ExecuteAffectedExecutor(InvocationContext ctx) in /_/src/dotnet-affected/Commands/Binding/InvocationContextExtensions.cs:line 37
   at Affected.Cli.Commands.AffectedRootCommand.<>c.<<-ctor>b__4_0>d.MoveNext() in /_/src/dotnet-affected/Commands/AffectedRootCommand.cs:line 39
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
```

it should be easy enough to convert that path to a fully qualified path, though I'm not sure if that should be done in the binder, or before calling `SolutionFile.Parse`

**Comment by leonardochaia** [comment]
Hi @hahn-kev , nice catch. This should have failed before, perhaps it is a regression.
I'll take a look
